### ISSUE TITLE
Javascript errors when trying to activate 'alerta' as destination

### ISSUE THREAD

**Issue by poffyna** [johnsusek/praeco#532]
## 🐛 Describe the bug

- Docker image and tag names for praeco and elastalert

praecoapp/praeco:1.8.13
praecoapp/elastalert-server:20230402

- Screen capture of praeco operation
![image](https://github.com/johnsusek/praeco/assets/52747085/3ee48522-e6a7-45c7-9933-040a85fe2ab7)

- No error is reported in elastalert-server. Only the gui produces javascript errors.

## 👀 Steps to reproduce
- Start editing any rule
- In the 'destinations' section, activate the 'Alerta' entry
- several javascript errors pop up

All other destinations can be activated without errors.
We have been using Praeco for some time now with mainly RocketChat as destination, and we are pleased with this.
But we want to add Alerta as additional destination, which fails.

## 🆗 Expected behavior
- 'Alerta' tab can be activated and populated without errors.

## Environments
Both elastalert-server and praeco run in docker containers.

**Comment by nsano-rururu** [comment]
@poffyna 
Thank you for using the alert notification function to Rocket.Chat. I added the alert notification function to Rocket.Chat to elastalert2. One of the maintainers of elastalert2.
I'll look into the praeco bug over the weekend. I'll release a new version over the weekend if it looks like it will be ready soon.

**Comment by nsano-rururu** [comment]
Fix
https://github.com/johnsusek/praeco/commit/c5171011e68adb6adb023ea7798f433d60705dc2

**Comment by nsano-rururu** [comment]
@poffyna 
Fixed version 1.8.14 has been released.
https://hub.docker.com/r/praecoapp/praeco/tags

**Comment by poffyna** [comment]
Thank you for the quick action.
I have downloaded and started the 'latest' docker containers, which indeed show the new version: 
![image](https://github.com/johnsusek/praeco/assets/52747085/05782459-3311-4e3c-9a3f-a8ce00a511f0)

However... the issue is still there: javascript/vue errors popping up as soon as I click the 'Alerta' destination . And same issue when going to the Alerta tab and filling/updating any of the values there.

**Comment by nsano-rururu** [comment]
@poffyna
Fixed version 1.8.15 has been released.
https://hub.docker.com/r/praecoapp/praeco/tags

**Comment by poffyna** [comment]
@nsano-rururu 
Version 1.8.15 indeed solves the javascript errors. Thanks!
